version: '3.8'

services:
  # InfluxDB per il backend
  influxdb:
    image: influxdb:1.8
    container_name: influxdb-backend
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=prometheus_metrics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: unless-stopped
    networks:
      - monitoring_network

  # Grafana per visualizzazione
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-backend
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    networks:
      - monitoring_network
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:

networks:
  monitoring_network:
    driver: bridge 