# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prometheus_remote_write.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_gen_import@@

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='prometheus_remote_write.proto',
  package='prometheus',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cprometheus_remote_write.proto\x12\tprometheus\"\x8c\x01\n\x0cWriteRequest\x12\x32\n\x06timeseries\x18\x01 \x03(\x0b\x32\".prometheus.TimeSeries\x12\x1a\n\x12metadata\x18\x03 \x03(\x0b\x32\x1e.prometheus.MetricMetadata\x12\x1a\n\x12accepted_response\x18\x02 \x01(\x0b\x32\x1e.prometheus.WriteResponse\x12\x10\n\x08\x64\x65\x62ug\x18\x04 \x01(\x08\"\x8c\x01\n\tTimeSeries\x12\x1d\n\x06labels\x18\x01 \x03(\x0b\x32\r.prometheus.Label\x12\x1d\n\x06samples\x18\x02 \x03(\x0b\x32\r.prometheus.Sample\x12\x1e\n\x07\x65xemplars\x18\x03 \x03(\x0b\x32\r.prometheus.Exemplar\x12\x1f\n\x08histograms\x18\x04 \x03(\x0b\x32\r.prometheus.Histogram\"\x1e\n\x05Label\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x06Sample\x12\t\n\x01value\x18\x01 \x01(\x01\x12\t\n\x01timestamp\x18\x02 \x01(\x03\"\x1e\n\x07\x45xemplar\x12\t\n\x01value\x18\x01 \x01(\x01\x12\x08\n\x06labels\x18\x02 \x03(\x0b\x32\r.prometheus.Label\"\x1e\n\tHistogram\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\"\x1e\n\x0eMetricMetadata\x12\x0c\n\x04type\x18\x01 \x01(\x0e\x32\x08.MetricType\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1e\n\rWriteResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t*.\n\nMetricType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x43OUNTER\x10\x01\x12\x08\n\x04GAUGE\x10\x02')
)

_METRICTYPE = _descriptor.EnumDescriptor(
  name='MetricType',
  full_name='prometheus.MetricType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COUNTER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAUGE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=0,
  serialized_end=0,
  create_key=_descriptor._internal_create_key,
)
_sym_db.RegisterEnumDescriptor(_METRICTYPE)

_WRITEREQUEST = _descriptor.Descriptor(
  name='WriteRequest',
  full_name='prometheus.WriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeseries', full_name='prometheus.WriteRequest.timeseries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='prometheus.WriteRequest.metadata', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accepted_response', full_name='prometheus.WriteRequest.accepted_response', index=2,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='debug', full_name='prometheus.WriteRequest.debug', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=44,
  serialized_end=184,
)

_TIMESERIES = _descriptor.Descriptor(
  name='TimeSeries',
  full_name='prometheus.TimeSeries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='prometheus.TimeSeries.labels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='samples', full_name='prometheus.TimeSeries.samples', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exemplars', full_name='prometheus.TimeSeries.exemplars', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='histograms', full_name='prometheus.TimeSeries.histograms', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=186,
  serialized_end=326,
)

_LABEL = _descriptor.Descriptor(
  name='Label',
  full_name='prometheus.Label',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='prometheus.Label.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='prometheus.Label.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=328,
  serialized_end=358,
)

_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='prometheus.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='prometheus.Sample.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='prometheus.Sample.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=360,
  serialized_end=390,
)

_EXEMPLAR = _descriptor.Descriptor(
  name='Exemplar',
  full_name='prometheus.Exemplar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='prometheus.Exemplar.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='labels', full_name='prometheus.Exemplar.labels', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=392,
  serialized_end=422,
)

_HISTOGRAM = _descriptor.Descriptor(
  name='Histogram',
  full_name='prometheus.Histogram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='prometheus.Histogram.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=424,
  serialized_end=454,
)

_METRICMETADATA = _descriptor.Descriptor(
  name='MetricMetadata',
  full_name='prometheus.MetricMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='prometheus.MetricMetadata.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='prometheus.MetricMetadata.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=456,
  serialized_end=486,
)

_WRITERESPONSE = _descriptor.Descriptor(
  name='WriteResponse',
  full_name='prometheus.WriteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='prometheus.WriteResponse.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=488,
  serialized_end=518,
)

_WRITEREQUEST.fields_by_name['timeseries'].message_type = _TIMESERIES
_WRITEREQUEST.fields_by_name['metadata'].message_type = _METRICMETADATA
_WRITEREQUEST.fields_by_name['accepted_response'].message_type = _WRITERESPONSE
_WRITEREQUEST.containing_type = None
_TIMESERIES.fields_by_name['labels'].message_type = _LABEL
_TIMESERIES.fields_by_name['samples'].message_type = _SAMPLE
_TIMESERIES.fields_by_name['exemplars'].message_type = _EXEMPLAR
_TIMESERIES.fields_by_name['histograms'].message_type = _HISTOGRAM
_TIMESERIES.containing_type = None
_LABEL.containing_type = None
_SAMPLE.containing_type = None
_EXEMPLAR.fields_by_name['labels'].message_type = _LABEL
_EXEMPLAR.containing_type = None
_HISTOGRAM.containing_type = None
_METRICMETADATA.fields_by_name['type'].enum_type = _METRICTYPE
_METRICMETADATA.containing_type = None
_WRITERESPONSE.containing_type = None
_METRICTYPE.containing_type = None

DESCRIPTOR.message_types_by_name['WriteRequest'] = _WRITEREQUEST
DESCRIPTOR.message_types_by_name['TimeSeries'] = _TIMESERIES
DESCRIPTOR.message_types_by_name['Label'] = _LABEL
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
DESCRIPTOR.message_types_by_name['Exemplar'] = _EXEMPLAR
DESCRIPTOR.message_types_by_name['Histogram'] = _HISTOGRAM
DESCRIPTOR.message_types_by_name['MetricMetadata'] = _METRICMETADATA
DESCRIPTOR.message_types_by_name['WriteResponse'] = _WRITERESPONSE
DESCRIPTOR.enum_types_by_name['MetricType'] = _METRICTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WriteRequest = _reflection.GeneratedProtocolMessageType('WriteRequest', (_message.Message,), dict(
  DESCRIPTOR = _WRITEREQUEST,
  __module__ = 'prometheus_remote_write_pb2'
  # @@protoc_gen_register@@
  ))
_sym_db.RegisterMessage(WriteRequest)

TimeSeries = _reflection.GeneratedProtocolMessageType('TimeSeries', (_message.Message,), dict(
  DESCRIPTOR = _TIMESERIES,
  __module__ = 'prometheus_remote_write_pb2'
  # @@protoc_gen_register@@
  ))
_sym_db.RegisterMessage(TimeSeries)

Label = _reflection.GeneratedProtocolMessageType('Label', (_message.Message,), dict(
  DESCRIPTOR = _LABEL,
  __module__ = 'prometheus_remote_write_pb2'
  # @@protoc_gen_register@@
  ))
_sym_db.RegisterMessage(Label)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLE,
  __module__ = 'prometheus_remote_write_pb2'
  # @@protoc_gen_register@@
  ))
_sym_db.RegisterMessage(Sample)

Exemplar = _reflection.GeneratedProtocolMessageType('Exemplar', (_message.Message,), dict(
  DESCRIPTOR = _EXEMPLAR,
  __module__ = 'prometheus_remote_write_pb2'
  # @@protoc_gen_register@@
  ))
_sym_db.RegisterMessage(Exemplar)

Histogram = _reflection.GeneratedProtocolMessageType('Histogram', (_message.Message,), dict(
  DESCRIPTOR = _HISTOGRAM,
  __module__ = 'prometheus_remote_write_pb2'
  # @@protoc_gen_register@@
  ))
_sym_db.RegisterMessage(Histogram)

MetricMetadata = _reflection.GeneratedProtocolMessageType('MetricMetadata', (_message.Message,), dict(
  DESCRIPTOR = _METRICMETADATA,
  __module__ = 'prometheus_remote_write_pb2'
  # @@protoc_gen_register@@
  ))
_sym_db.RegisterMessage(MetricMetadata)

WriteResponse = _reflection.GeneratedProtocolMessageType('WriteResponse', (_message.Message,), dict(
  DESCRIPTOR = _WRITERESPONSE,
  __module__ = 'prometheus_remote_write_pb2'
  # @@protoc_gen_register@@
  ))
_sym_db.RegisterMessage(WriteResponse) 