apiVersion: v1
kind: Service
metadata:
  name: prometheus-loadbalancer
  namespace: istio-system
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
